config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :golfers
  post 'leaderboards/single_entry', to: 'leaderboards#single_entry'
  post 'golfers/create', to: 'golfers#create'
  get 'leaderboards', to: 'leaderboards#index'
  get 'flights', to: 'flights#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_and_belongs_to_many :golfers
end

app/models/golfer.rb
class Golfer < ApplicationRecord
  self.primary_key = "player_id"

  has_many :leaderboards
  has_and_belongs_to_many :flights
  # has_and_belongs_to_many :user_submissions
end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
  belongs_to :golfer, primary_key: "player_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable
  include ActiveModel::SecurePassword
  validates :email, presence: true
  # has_secure_password
  # has_and_belongs_to_many :user_submissions
end

app/models/user_submission.rb
class UserSubmission < ApplicationRecord
  belongs_to :golfer, primary_key: "player_id"
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :authenticate_user!

  def index
    @flights = Flight.all
  end
end

app/controllers/golfers_controller.rb
class GolfersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_golfer, only: %i[ show edit update destroy ]
  helper_method :flight_groups
  before_action :authenticate_user!

  # GET /golfers or /golfers.json
  def index
    @golfers = Golfer.all.sort_by do |golfer|
      if golfer.world_ranking == "Unranked"
        golfer.world_ranking = 200
      elsif golfer.world_ranking == "Amateur"
        golfer.world_ranking = 300
      else
        golfer.world_ranking.to_i
      end
    end
  end

  # GET /golfers/1 or /golfers/1.json
  def show
  end

  # GET /golfers/new
  def new
    @golfer = Golfer.new
  end

  # GET /golfers/1/edit
  def edit
  end

  # POST /golfers or /golfers.json
  def create
    @golfer = Golfer.new(golfer_params)

    respond_to do |format|
      if @golfer.save
        format.html { redirect_to golfer_url(@golfer), notice: "Golfer was successfully created." }
        format.json { render :show, status: :created, location: @golfer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @golfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /golfers/1 or /golfers/1.json
  def update
    respond_to do |format|
      if @golfer.update(golfer_params)
        format.html { redirect_to golfer_url(@golfer), notice: "Golfer was successfully updated." }
        format.json { render :show, status: :ok, location: @golfer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @golfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /golfers/1 or /golfers/1.json
  def destroy
    @golfer.destroy

    respond_to do |format|
      format.html { redirect_to golfers_url, notice: "Golfer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def flight_groups(id)
    id == nil ? "" : Flight.find_by(id: id).name
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_golfer
    @golfer = Golfer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def golfer_params
    params.require(:golfer).permit(:player_id, :name, :world_ranking, :flight_ids)
  end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :authenticate_user!

  def single_entry
    data = {
      golfer_id: params["golfer_id"],
      year: params["year"],
      position: params["position"],
      round_one: params["round_one"],
      round_two: params["round_two"],
      round_three: params["round_three"],
      round_four: params["round_four"],
      total: params["total"],
      earnings: params["earnings"]
    }

    golfer_scorecard = Leaderboard.find_by(golfer_id: data[:golfer_id], year: data[:year])
    golfer_scorecard.nil? ? leaderboard_entry(data) : update_leaderboard_entry(golfer_scorecard, data)
  end

  def index
    @leaderboards = Leaderboard.all
  end

  private

  def leaderboard_entry(golfer_data)
    Leaderboard.create!(golfer_id: golfer_data[:golfer_id],
      year: golfer_data[:year],
      position: golfer_data[:position],
      round_one: golfer_data[:round_one],
      round_two: golfer_data[:round_two],
      round_three: golfer_data[:round_three],
      round_four: golfer_data[:round_four],
      total: golfer_data[:total],
      earnings: golfer_data[:earnings])
    render status: 200, json: {message: "Success"}
  rescue ActiveRecord::RecordInvalid => e
    render status: 422, json: {message: e}
  end

  def update_leaderboard_entry(golfer_data, entry_data)
    entry_data = entry_data.except(:golfer_id, :year).compact
    entry_data.each do |key, value|
      golfer_data[key] = value
    end
    golfer_data.save!
    render status: 200, json: {message: "Success"}
  rescue ActiveRecord::RecordInvalid => e
    render status: 422, json: {message: e}
  end
end

app/controllers/user_submission_controller.rb
class UserSubmissionController < ApplicationController
  def user_selections
    # endpoint for user submissions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/golfers_helper.rb
module GolfersHelper
end

app/helpers/grouping_helper.rb
module GroupingHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/helpers/user_submission_helper.rb
module UserSubmissionHelper
end

app/views/flights/index.html.erb
<h1>Flights</h1>
<div><%= button_to "logout", destroy_user_session_path, method: :delete %></div>
<div>
  <% @flights.each do |flight| %>
    <p><%= flight.name %></p>
    <table>
      <thead>
        <tr>
          <th>World Ranking</th>
          <th>Golfer</th>
        </tr>
      </thead>
      <tbody>
        <% golfer_ids = Flight.find_by(id: flight.id).golfer_ids%>
        <% golfer_ids.each do |gid| %>
        <% golfer = Golfer.find_by(player_id: gid) %>
        <tr>
          <td><%= golfer.world_ranking %></td>
          <td><%= golfer.name %></td>
        <% end %>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/golfers/_form.html.erb
<%= form_with(model: golfer) do |form| %>
  <% if golfer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(golfer.errors.count, "error") %> prohibited this golfer from being saved:</h2>

      <ul>
        <% golfer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :player_id, style: "display: block" %>
    <%= form.text_field :player_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :flight, style: "display: block" %>
    <%= form.select :flight_ids, Flight.all.collect { |f| [f.name, f.id] }, include_blank: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/golfers/_golfer.html.erb
<div id="<%= dom_id golfer %>">
  <td><%= golfer.world_ranking%></td>
  <td><%= golfer.name%></td>
  <td><%= flight_groups(golfer.flight_ids[0])%>
</div>

app/views/golfers/edit.html.erb
<h1>Editing golfer</h1>

<%= render "form", golfer: @golfer %>

<br>

<div>
  <%= link_to "Show this golfer", @golfer %> |
  <%= link_to "Back to golfers", golfers_path %>
</div>

app/views/golfers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Golfers</h1>
<%= render "/layouts/navigation" %>
<div id="golfers">
  <table>
    <thead>
      <tr>
        <th>World Ranking</th>
        <th>Name</th>
        <th>Flight Group</th>
        <th>Edits</th>
      </tr>
    </thead>
    <% @golfers.each do |golfer| %>
    <tbody>
      <tr>
        <%= render golfer %>
        <td><%= link_to "Show this golfer", golfer %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

<%= link_to "New golfer", new_golfer_path %>

app/views/golfers/new.html.erb
<h1>New golfer</h1>

<%= render "form", golfer: @golfer %>

<br>

<div>
  <%= link_to "Back to golfers", golfers_path %>
</div>

app/views/golfers/show.html.erb
<p style="color: green"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>World Ranking</th>
      <th>Name</th>
      <th>Flight Group</td>
      <th>Edits</th>
    </tr>
  </thead>
  <tbody>
    <%= render @golfer %>
    <td>
      <div><%= link_to "Edit this golfer", edit_golfer_path(@golfer) %></div> 
      <div><%= button_to "Destroy", @golfer, method: :delete %></div>
    </td>
  </tbody>
</table>

<div>
  
</div>
<div>
  <%= link_to "Back to golfers", golfers_path %>
</div>

app/views/layouts/_navigation.html.erb
<nav>
  <div>
    <a href="/">Home</a>
    <a href="/golfers">Golfers</a>
    <a href="/flights">Flights</a>
  </div>
  <div>
    <%= button_to "logout", destroy_user_session_path, method: :delete %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MastersPoolApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leaderboards/_leaderboard.html.erb
<div id="<%= dom_id leaderboard %>">
    <table>
        <tr>
            <th>Golfer</th>
            <th>Position</th>
            <th>Round 1</th>
            <th>Round 2</th>
            <th>Round 3</th>
            <th>Round 4</th>
            <th>Total</th>
            <th>Earnings</th>
        </tr>
        <tr>
            <td><%= leaderboard.golfer.name %></td>
            <td><%= leaderboard.position %></td>
            <td><%= leaderboard.round_one %></td>
            <td><%= leaderboard.round_two %></td>
            <td><%= leaderboard.round_three %></td>
            <td><%= leaderboard.round_four %></td>
            <td><%= leaderboard.total %></td>
            <td><%= leaderboard.earnings %></td>
        </tr>
    </table>
</div>

app/views/leaderboards/index.html.erb
<h1>Leaderboards</h1>

<div>
    <% @leaderboards.each do |leaderboard| %>
        <%= render leaderboard %>
    <% end %>
</div>